### ISSUE TITLE
Is this project alive?:)

### ISSUE THREAD

**Issue by InsanusMokrassar** [mminke/kotlin-compose-web-material3#2]
It looks like the thing which is must-have in projects which wish to use as native as possible material 3. Unfortunatelly, as I see, this project is based on kotlin 1.8.20 and old compose. Is there any chance for update of project and following support?

**Comment by mminke** [comment]
Hi, thx for the question. I started the project because I was missing MD3 components for compose web. I have multiple projects and this one got a bit to the background. I think the kotlin version is not that problematic, the compose version is however. And more importantly I did not yet update the code to the latest code of the google MD3 web component team.

I would really love to improve things, but time for me is limited. I would appreciate any help so if you want to help out please let me know.

**Comment by InsanusMokrassar** [comment]
> Hi, thx for the question. I started the project because I was missing MD3 components for compose web. I have multiple projects and this one got a bit to the background. I think the kotlin version is not that problematic, the compose version is however. And more importantly I did not yet update the code to the latest code of the google MD3 web component team.
> 
> I would really love to improve things, but time for me is limited. I would appreciate any help so if you want to help out please let me know.

Thank you for your answer :) I understand yours limits of time, I have the same problem :) Happy new year and I wish you to have more time to complete your plans :)
